name: On Pull Request
on:
  merge_group:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
concurrency:
  group: on-pull-request_${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  codeql:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/codeql.yml
    

